"""
Guide for regenerating access tokens after permission changes
"""

print("X API Permission Update Guide")
print("="*50)
print()
print("Since you've updated your app permissions to 'Read and Write',")
print("you may need to regenerate your access tokens for the changes")
print("to take effect in the API.")
print()
print("Steps to regenerate access tokens:")
print("1. Go to your X Developer Portal: https://developer.twitter.com/")
print("2. Navigate to your app's 'Keys and tokens' section")
print("3. Scroll down to the 'Access token and secret' section")
print("4. Click 'Regenerate' next to your access tokens")
print("5. Confirm the regeneration when prompted")
print("6. Copy the new Access Token and Access Token Secret")
print("7. Update your x_api_config.json file with the new values")
print()
print("After updating with new tokens, restart the integration:")
print("python hub_x_integration.py")
print()
print("Note: Sometimes permission changes take a few minutes to fully")
print("propagate through X's systems, so wait a few minutes after")
print("regenerating tokens before testing again.")
print()
print("If regenerating tokens doesn't work, you may need to:")
print("- Re-authorize your app completely")
print("- Or wait 15-30 minutes for the permission changes to propagate")