import requests
import subprocess
import psutil

print('=== COMPREHENSIVE SYSTEM VERIFICATION ===')

# Check UI server
try:
    ui_stats = requests.get('http://localhost:8083/api/stats', timeout=5).json()
    ui_posts = requests.get('http://localhost:8083/api/posts', timeout=5).json()
    print('UI Server Status: OK')
    print(f'  Posts Count: {ui_stats["total_posts"]}')
    print(f'  Avg Quality (calc): {ui_stats["avg_quality_score"]}')
    print(f'  Recent Posts with Calc Quality: {len(ui_posts)}')
    if ui_posts:
        calc_avg = sum(p["quality_score"] for p in ui_posts) / len(ui_posts)
        print(f'  Calc Avg from Posts: {calc_avg:.2f}')
except Exception as e:
    print(f'UI Server Issue: {e}')

print()

# Check backend
try:
    backend_posts = requests.get('http://localhost:8082/api/posts', timeout=5).json()
    print(f'Backend Status: OK')
    print(f'  Total Posts: {len(backend_posts)}')
    zero_scores = sum(1 for p in backend_posts if p.get("quality_score") == 0)
    print(f'  Posts with Zero Quality Score: {zero_scores}')
    if len(backend_posts) > 0:
        print(f'  Percentage with Zero Scores: {zero_scores/len(backend_posts)*100:.1f}%')
except Exception as e:
    print(f'Backend Issue: {e}')

print()

# Check running processes
running_procs = []
for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
    try:
        cmd = ' '.join(proc.info['cmdline']) if proc.info['cmdline'] else ''
        if any(name in cmd.lower() for name in ['hub', 'x_', 'tweet', 'curator', 'integration']):
            running_procs.append((proc.info['name'], cmd))
    except:
        pass

print(f'Running Related Processes: {len(running_procs)}')
for name, cmd in running_procs:
    print(f'  {name}: {cmd}')

print()

# Check if there are any issues with the integration
print('=== POTENTIAL ISSUES IDENTIFIED ===')
print('1. Quality scores are calculated on-the-fly but not persisted in backend')
print('2. X integration appears to be inactive')
print('3. Backend shows all posts with quality=0, but UI calculates them')
print('4. The system may be generating content but not properly curating/sharing it')

print()
print('=== ANALYSIS ===')
print('The hub is technically running but may not be operating as intended:')
print('- Content is being generated by agents')
print('- Quality assessment happens at UI layer but not stored permanently')
print('- Integration with X platform may not be active')
print('- The monetization pipeline may not be functioning')
print()
print('The system needs proper quality score persistence and active integration.')